CREATE TABLE `emails` (
	`id` text PRIMARY KEY NOT NULL,
	`domain` text,
	`message_from` text,
	`message_to` text,
	`headers` text NOT NULL,
	`from` text NOT NULL,
	`sender` text,
	`reply_to` text,
	`delivered_to` text,
	`return_path` text,
	`to` text,
	`cc` text,
	`bcc` text,
	`subject` text,
	`message_id` text,
	`in_reply_to` text,
	`references` text,
	`date` text,
	`html` text,
	`text` text,
	`attachments` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
